services:
  - type: web
    name: rails-watch-list
    env: ruby
    plan: free
    buildCommand: bundle install && yarn install && bundle exec rake assets:precompile
    startCommand: bundle exec rails server -p 3000

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-watch-list-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: rails-watch-list-db
    plan: free
